### ISSUE TITLE
OSX latest 0.1.1 doesn't work

### ISSUE THREAD

**Issue by fbacker** [bambocher/pocketsphinx-python#15]
Trying to install with python3 on Mac OS X 10.11.6

	$ git clone --recursive https://github.com/bambocher/pocketsphinx-python
	$ cd pocketsphinx-python
	$ python3 setup.py install

Crashes

	/usr/bin/clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c deps/sphinxbase/src/libsphinxad/ad_oss.c -o build/temp.macosx-10.6-intel-3.5/deps/sphinxbase/src/libsphinxad/ad_oss.o
	deps/sphinxbase/src/libsphinxad/ad_oss.c:63:10: fatal error: 'sys/soundcard.h' file not found
	#include <sys/soundcard.h>
	         ^
	1 error generated.
	error: command '/usr/bin/clang' failed with exit status 1

**Comment by MisterVulcan** [comment]
Same here with python2.7 (macports) on OS X 10.10.5:

`usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c deps/sphinxbase/src/libsphinxad/ad_oss.c -o build/temp.macosx-10.10-x86_64-2.7/deps/sphinxbase/src/libsphinxad/ad_oss.o
deps/sphinxbase/src/libsphinxad/ad_oss.c:63:10: fatal error: 'sys/soundcard.h' file not found
#include <sys/soundcard.h>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1`

Apparently there's an API issue with how OS X handles audio compared to Linux:

[http://www.macosxaudio.com/forums/viewtopic.php?f=10&t=17088](url)
and
[https://trac.macports.org/ticket/44988](url)

Either that or pocketsphinx-python just doesn't support Macs *yet* :-)

**Comment by nshmyrev** [comment]
This is a bug introduced in fce806651ebc4b3435ce204a7ba07f57e2271fae, actually you should not compile that file at all. You can revert to earlier version to make it work.

**Comment by fbacker** [comment]
uninstalled pocketsphinx, then installed

    pip3 install pocketsphinx==0.1.0

Seems to getting a little longer before a crash =)

**Comment by nshmyrev** [comment]
Provide the updated log please

**Comment by fbacker** [comment]
Now I've had some time to clean up the code and try it out.
So on **OSX 10.11** it works fine if using pocketsphinx 0.1.0 (not latest 0.1.1)

    pip3 install pocketsphinx==0.1.0

Would be great if someone else can confirm this, then you can update the readme with an osx note. Keep up the great work and thanks.

**Comment by nshmyrev** [comment]
Thanks for testing @fbacker, however, the bug is still valid. It would be great if you reopen it and give it a proper title.

Thanks

**Comment by bambocher** [comment]
Sorry for the long answer. Thanks for testing @MisterVulcan and @fbacker. Thanks for the replies @nshmyrev. In 0.1.1 really had a problem on Mac OS X. Please try the new version 0.1.3. It fixed this problem. Also added higher-level classes. Examples can be seen [here](https://github.com/bambocher/pocketsphinx-python). I hope they will be useful. 1.1.0 removed from PyPI.

**Comment by fbacker** [comment]
Sorry for the long delay @bambocher, too much at work. I've testet 0.1.3 and it works great. Good work :)
